### PR TITLE
Fix to get PRE test working on ADESP_TEST on Cheyenne

### LINKED ISSUE #1622: PRE test not working for ADESP_TEST
Due to changes in the data models, the PRE test stopped working for ADESP_TEST.

### PR DESCRIPTION
**Pull request by gold2718**
Modified PRE test to look for no pause signal situation.
Modified ADESP_TEST variable change to get output change with new docn aquaplanet.
Added ADESP_TEST to cime_developer suite.

Test suite: scripts_regression_tests.py on Yellowstone, Cheyenne, and Hobart
Test baseline: NA
Test namelist changes: NA
Test status: bit for bit

Fixes #1622

User interface changes?: No

Update gh-pages html (Y/N)?: N

Code review:

### CODE REVIEW

File: src/components/data_comps/desp/desp_comp_mod.F90 [hunk 1]
```diff
@@ -427,6 +427,13 @@ subroutine desp_comp_run(EClock, case_name, pause_sig, atm_resume,          &
 
     call t_startf('desp_mode')
 
+    if (.not. ANY(pause_sig)) then
+      if ((my_task == master_task) .and. (loglevel > 0)) then
```
Comment (jedwards4b) [inline src/components/data_comps/desp/desp_comp_mod.F90]: Can we get rid of the loglevel requirement in this and other locations in desp and just allways write these messages to the desp.log?

Comment (gold2718) [inline src/components/data_comps/desp/desp_comp_mod.F90]: Okay for this warning, what others? Check:
Lines 505, 512, 562, and 676

**Comment by jedwards4b** [comment]
I would say all of them, it's not an over abundance of output.
